name: avrdude_windows build and push script
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Install pip
        run: sudo apt install -y python3-pip python3-setuptools unzip wget git

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install python dependencies
        run: pip3 install -r ${{ github.workspace }}/requirements.txt



      - name: Download and unzip avrdude
        run: |
          cd ${{ github.workspace }}/avrdude_windows/avrdude_binaries
          mkdir -p x32
          cd x32
          wget "https://github.com/avrdudes/avrdude/releases/download/v7.1/avrdude-v7.1-windows-x86.zip"
          unzip avrdude-v7.1-windows-x86.zip
          rm avrdude-v7.1-windows-x86.zip
          
          cd ..
          mkdir -p x64
          cd x64
          wget "https://github.com/avrdudes/avrdude/releases/download/v7.1/avrdude-v7.1-windows-x64.zip"
          unzip avrdude-v7.1-windows-x64.zip
          rm avrdude-v7.1-windows-x64.zip

      - name: Build wheel
        run: python3 -m build
        working-directory: ${{ github.workspace }}